# Generated by Django 5.2 on 2025-04-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kur.currencyname'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currencyname',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
